### ISSUE TITLE
Authorization on Enum Values

### ISSUE THREAD

**Issue by micahlisonbee** [exAspArk/graphql-guard#11]
I'd like to be able to restrict certain enum input values to only super_admin users. Is there a way to do something like this? (This doesn't work obviously)

```ruby
Types::OrganizationTypeEnumType = GraphQL::EnumType.define do
  name 'OrganizationTypeEnumType'
  description 'Enum for the possible organization types'

  value('PROVIDER', 'provider', value: 'provider'), guard: ->(obj, _args, ctx) { ctx[:current_user].super_admin? }
  value('CUSTOMER', 'customer', value: 'customer')
  value('THIRD_PARTY', 'third_party', value: 'third_party')
end
```

**Comment by exAspArk** [comment]
@micahlisonbee hey, thanks for opening the issue!

Unfortunately, it's not possible because `graphql-ruby` gem [doesn't allow](https://github.com/rmosolgo/graphql-ruby/blob/58577377e9ac59f03b0fb62fc71a0ed58d878c17/lib/graphql/define/assign_enum_value.rb#L6) passing custom tags like `guard` for the `value` method. I might open an issue in https://github.com/rmosolgo/graphql-ruby.

If you want, you can try to use [GraphQL::Schema::Warder](http://www.rubydoc.info/gems/graphql/1.7.7/GraphQL/Schema/Warden) feature with custom filters. For example:

```ruby
# controller
query = ...
admin_filter = AdminFilter.new(current_user)
result = YourSchema.execute(query, except: admin_filter)

# admin_filter
class AdminFilter
  def initialize(user)
    @user = user
  end

  def call(member, ctx)
    member.name == 'PROVIDER' && member.description == 'provider' && member.value == 'provider' && ctx[:current_user].super_admin? 
  end
end

```

**Comment by micahlisonbee** [comment]
@exAspArk thanks for the thoughtful response. I think filtering is probably the to go for now as you've outlined in your `AdminFilter` example. I'll give it a go and brainstorm on other options. 

Thanks again.
