### ISSUE TITLE
Undefined method guard for Resolvers Class

### ISSUE THREAD

**Issue by davidfilip** [exAspArk/graphql-guard#2]
I am trying to use guard inside the Mutation, using Resolvers class: 

```ruby
class Resolvers::UpdateExample < GraphQL::Function
  argument :id, !types.ID
  argument :example, !Inputs::ExampleInput

  type Types::ExampleType

  guard ->(obj, args, ctx) { 
      true
    }

  def call(obj,args,ctx)
    puts "hello world"
  end
end
```

When I try to call this mutation I get error:

>  Failure/Error:
       guard ->(obj, args, ctx) { 
         ..
     
     NoMethodError:
       undefined method `guard' for Resolvers::UpdateExample:Class

**Comment by exAspArk** [comment]
Hey, @davidfilip!

Thank you so much for reporting the issue!

To be honest, I haven't used `GraphQL::Function` before. Mostly lambdas or resolve objects like:

```ruby
field :something, resolve: UpdateExample.new

class UpdateExample
  def call(obj, args, ctx)
    # ...
  end
end
```

For now, you probably have these 2 options:

* Use `guard` on the field

```ruby
field :something, function: UpdateExample.new do
  guard ->(obj, args, ctx) { true }
end
```

* Or define your authorization logic in the policy object:

```ruby
field :something, function: UpdateExample.new

class GraphqlPolicy
  RULES = {
    Types::ExampleType => {
      something: ->(obj, args, ctx) { true }
    }
  }

  def self.guard(type, field)
    RULES.dig(type, field)
  end
end

Schema = GraphQL::Schema.define do
  # ...
  use GraphQL::Guard.new(policy_object: GraphqlPolicy)
end
```

I'll try to investigate whether it's possible to extend `GraphQL::Function` in order to use inline `guard` without monkey patching next week 🙌

**Comment by exAspArk** [comment]
@davidfilip unfortunately, `GraphQL:: Function` doesn't support extending the interface similarly to [Extending the DSL](http://graphql-ruby.org/schema/extending_the_dsl.html) without monkey patching the class.

So, I'd suggest defining `guard` with a policy object or on the Type level, e.g.:

```ruby
QueryType = GraphQL::ObjectType.define do
  field :something, guard: ->(obj, args, ctx) { true }, function: UpdateExample.new
end
```
